### ISSUE TITLE
DaPhone Exercise

### ISSUE THREAD

**Issue by svozza** [dwayne/haskell-programming#2]
Hey there, first of all, thanks for posting your solutions to the book, it's been very helpful for me to compare my answers to yours as I've been working my way through the material (I'm only on chapter 12). I noticed that you haven't done the `mostPopularLetter`, `costliestLetter`, `coolestLetter` and `coolestWord` functions in the DaPhone exercise. 

For `mostPopularLetter` I spent a lot of time making this really complicated function that attempted to operate on the letters _after_ they'd been converted to key presses but I then realised that that's not what they were asking for and I just dealt with the raw string before working out the costliest letter. I could share my solution in the form of a PR if you want or given what I've said you could probably do it yourself now.

**Comment by dwayne** [comment]
Thanks, but it's okay. I'd try it for myself first when I circle back to that chapter.

**Comment by svozza** [comment]
Fair enough. Best of luck!
