### ISSUE TITLE
Ch11: isSubsequenceOf function is incorrect

### ISSUE THREAD

**Issue by Bassov** [dwayne/haskell-programming#4]
https://github.com/dwayne/haskell-programming/blob/c618817708524ce2f15fc4100bdc2372b1f53370/ch11/AsPatterns.hs#L5

Hi! There is a problem in a function, if we eval isSubsequenceOf "bl" "baaal" it would return True.

I've solve this task like this:
```
isSubsequenceOf :: Eq a => [a] -> [a] -> Bool
isSubsequenceOf xs ys = go xs ys
    where
        go [] _          = True
        go _ []          = False
        go (a:as) (b:bs) = (a == b && go as bs) || go xs bs
```
So I haven't found usage for xs@(x:_) syntax in this task:(

**Comment by dwayne** [comment]
@Bassov You're right. The `s` in my solution doesn't capture the original string at all times. Thanks for the contribution.
